### PR TITLE
Add homepage contents and style

### PR DESCRIPTION
**Pull request by Abiodun-Shittu**

### CODE REVIEW

**Comment by IyiKuyoro** [comment]
Is this ready for review @Abiodun-Shittu?

**Comment by Abiodun-Shittu** [comment]
> Is this ready for review @Abiodun-Shittu?

yes it is @IyiKuyoro

**Comment by IyiKuyoro** [comment]
Please add a PR template to this repo. [Check this out for that.](https://docs.github.com/en/enterprise/2.14/user/articles/creating-a-pull-request-template-for-your-repository)

Use the below as the template
```
## title

_short description of pr_

### Tasks to be Completed

- [ ] Task 1
- [ ] Task 2

### What Needs to be Done to QA This PR Locally

- step 1
- step 2
```

**Comment by IyiKuyoro** [comment]
The template will help with your PR descriptions. Each PR should always have a description.

**Review by IyiKuyoro — CHANGES_REQUESTED** [review]
You did well on this. Just a little request here. Seems like the home page does not fill the entire screen on my laptop.

Screenshot from 2020-08-25 16-32-27

**Comment by Abiodun-Shittu** [comment]
> You did well on this. Just a little request here. Seems like the home page does not fill the entire screen on my laptop.
> 
> Screenshot from 2020-08-25 16-32-27

ok, will fix this

**Review by IyiKuyoro — APPROVED** [review]
I will give more context around the PR template thing when we discuss this weekend.

**Comment by IyiKuyoro** [comment]
Please feel free to merge!

**Comment by Abiodun-Shittu** [comment]
> Please feel free to merge!

okay

**Comment by Abiodun-Shittu** [comment]
> I will give more context around the PR template thing when we discuss this weekend.

alright boss @IyiKuyoro

**Pull request merged**
